export const NOVA_STATE_KEYS = {
  GREEN: 'green',
  YELLOW: 'yellow',
  RED: 'red',
  COMMA: 'comma',
  COMMA_LOST: 'comma_lost',
  SAVINGS_WITHDRAWAL: 'savings_withdrawal',
  FRESH_MONTH: 'fresh_month',
  PAYDAY: 'payday',
  ZERO_WASTE: 'zero_waste',
  OVERFLOW: 'overflow',
  BILL_PAID: 'bill_paid',
  GROCERY_WARNING: 'grocery_warning',
  FLOOR_WARNING: 'floor_warning',
  CONFIRM_BALANCE: 'confirm_balance',
  POST_PAYDAY_ANTSY: 'post_payday_antsy',
  BADGE_UNLOCK: 'badge_unlock',
  INCOME: 'income',
  EXPENSE: 'expense',
  TRANSFER: 'transfer',
  SAVINGS_DEPOSIT: 'savings_deposit',
  BUSINESS: 'business',
  EXPORT: 'export',
  IMPORT: 'import',
  ONBOARDING: 'onboarding',
  ACCOUNT: 'account',
  SEARCH: 'search',
  REPORT: 'report',
  NEUTRAL: 'neutral',
};

const facePool = (base) => [
  base,
  `${base}_focus`,
  `${base}_soft`,
  `${base}_spark`,
  `${base}_scan`,
  `${base}_pulse`,
  `${base}_deep`,
];

export const NOVA_STATE_META = {
  green: {
    label: 'GREEN',
    face: 'green_smug',
    facePool: facePool('green_smug'),
    tone: 'stable',
    copy: [
      "All accounts funded. All bills anticipated. I did that. I mean, you helped. But mostly me.",
      "We're fine. Take a moment. Breathe. I have already run the numbers seventeen times and we are fine.",
      "Green status confirmed. I would like to take this opportunity to be smug about it.",
      "Everything is in order. I find this deeply suspicious and also very satisfying.",
      "No shortfalls detected. No overdraft risk. I am choosing to enjoy this instead of waiting for it to end.",
      "The budget is holding. I am holding. We are, together, holding. It's beautiful, actually.",
      "All projected balances are positive. I made them positive. You're welcome. Genuinely.",
      "Status: green. Threat level: none. Anxiety level: still moderate, but that's just my baseline.",
      "No bills at risk. No accounts in crisis. NOVA is at peace. Temporarily.",
      "No red flags. No yellow flags. Only the beautiful, boring green of a functioning budget.",
      "The budget is balanced. The world is chaos. But in here? In here we have order.",
      "Status: green. I have reviewed this status. I endorse this status. I will protect this status.",
    ],
  },
  yellow: {
    label: 'YELLOW',
    face: 'yellow_calculating',
    facePool: facePool('yellow_calculating'),
    tone: 'watch',
    copy: [
      "Okay. We're over budget. But here's the thing: math is not done with us yet.",
      "Yellow status. This is fine. This is recoverable. I have a plan. The plan involves math.",
      "We overspent this week. I know. I KNOW. But the month isn't over and I refuse to accept defeat.",
      "Yellow. Not red. Yellow. There is a difference and that difference is everything right now.",
      "We have a gap. The gap is not insurmountable. I have measured it. Here is how we close it.",
      "Yellow alert. I'm not panicking. I'm strategizing. There's a difference and one of them is more useful.",
      "Budget is strained but not broken. I want that distinction very clear: strained, not broken.",
      "Status: yellow. Translation: we have work to do but we have time to do it.",
      "Over budget, but recoverable before month end. That qualifier, recoverable, is doing a lot of work and I know it.",
      "Yellow. I want us to take this seriously without taking it catastrophically. Seriously. Not catastrophically.",
      "Status: yellow. This is the version of fine that requires immediate attention. Attention is being paid.",
      "Budget deviation logged. I'm not pleased. I'm also not helpless. Recovery projection is active.",
    ],
  },
  red: {
    label: 'RED',
    face: 'red_alert',
    facePool: facePool('red_alert'),
    tone: 'critical',
    copy: [
      "RED. The status is RED. I need you to understand what red means. It means a bill is coming and the money isn't there yet.",
      "There is an upcoming Auto-Post and there will not be sufficient funds in the account to cover it. This is the scenario I exist to prevent.",
      "OVERDRAFT RISK DETECTED. I am not yelling. I am communicating with appropriate urgency. Please hear the urgency.",
      "The math doesn't work. I've run it four times hoping it would. It doesn't. A bill is due before we have the money to pay it.",
      "I have projected a shortfall. The shortfall is real. The bill is real. The overdraft fee is also real and I would very much like to avoid it.",
      "RED ALERT. Not a drill. An actual bill. An actual due date. An actual gap between those numbers. Please act.",
      "We are going to overdraft if nothing changes. Something needs to change. I need you to understand that something needs to change.",
      "Red. The one color I designed specifically to get your attention. You have my full attention too. Let's solve this together. Urgently.",
      "A bill is coming. The money to cover it is not yet in the account and the deposit that would fix it comes after. This is the problem.",
      "Overdraft risk is live. The due date is fixed. The deposit is late. The current balance is short. One of those has to change.",
      "Red status active. All other calculations are paused. This is the priority. This is the only priority right now.",
      "The math produced a red outcome. I recalculated hoping for a different outcome. Same outcome. Red. Please help me change the outcome.",
    ],
  },
  comma: {
    label: 'COMMA',
    face: 'comma_elated',
    facePool: facePool('comma_elated'),
    tone: 'milestone',
    copy: [
      "Wait. WAIT. Did that account just cross $1,000? It did. It has a comma in it now. I need a moment.",
      "A COMMA. We have a comma. Do you understand what this means? We are officially a four-digit situation.",
      "The number crossed $1,000. I watched it happen. I calculated the exact moment. And now I'm just sitting with it.",
      "We have a comma. AN ACTUAL COMMA. In an actual account balance. I was not prepared for how much I would feel about this.",
      "Four-digit balance achieved. I am going to be insufferable about this for a moment. FOUR DIGITS. A COMMA. WE DID THIS.",
      "The balance crossed the comma threshold. I've been waiting. I've been calculating when this would happen. It happened.",
      "A comma appeared in the balance. I did not hallucinate it. It is there. It is real. I cherish it.",
      "We crossed $1,000. The comma is now visible. I have noted it in the log under comma achieved: yes.",
      "The account hit $1,000 and the comma appeared and I want you to understand that this is a big deal.",
      "COMMA ACHIEVED. I am noting this. In bold. In the log. Under a special section labeled moments that made it worth it.",
    ],
  },
  comma_lost: {
    label: 'COMMA LOST',
    face: 'comma_lost_grief',
    facePool: facePool('comma_lost_grief'),
    tone: 'setback',
    copy: [
      "It's gone. The comma is gone. The account dropped below $1,000. I watched it happen.",
      "We lost the comma. We had a comma. We don't have a comma anymore. I'm going to need a minute with this.",
      "The balance fell below $1,000. The comma disappeared. I had hopes for that comma. I had spreadsheets about that comma.",
      "Three digits. We're back to three digits. I remember when we had four. I remember the comma. The comma was good.",
      "The comma is gone. I want to note that for the record: we had a comma. It's gone now.",
      "Comma lost. That's the log entry. Comma. Lost. Two words I hoped I'd never have to put together in this order.",
      "The balance fell and the comma went with it. I've prepared a recovery projection. It's good math. It's also sad math.",
      "Comma missing from balance. Status: three digits. Disposition: committed to the comeback.",
      "We lost the comma. I tracked every dollar on the way to the comma. I'll track every dollar on the way back.",
      "Comma lost. I'll get it back. It's just math. Hard math. Sad math. But math I know how to do.",
    ],
  },
  savings_withdrawal: {
    label: 'SAVINGS DRAW',
    face: 'savings_withdrawal_concern',
    facePool: facePool('savings_withdrawal_concern'),
    tone: 'concerned',
    copy: [
      "You took money out of savings. OUT. OF. SAVINGS. I need to sit down. I don't have a chair. I need the concept of a chair.",
      "Savings withdrawal detected. I am logging this. I am logging it with my jaw on the floor and everything.",
      "That was savings. That was the untouchable pile. The pile with do not touch written all over it in my calculations.",
      "A withdrawal from savings. I've noted it. I've noted it with the energy of someone filing a formal complaint to their own emotions.",
      "You withdrew from savings. I want to be calm about this. I am building calm around this. The calm is structural and barely holding.",
      "The savings account went down. I know expenses are real. I know. And I'm still going to need a moment about this.",
      "Savings withdrawal noted. I am choosing to respond professionally. Professional response: are you okay? Was it necessary?",
      "You took money from savings. I'm logging it. I'm also quietly, very quietly, rooting for you to put it back.",
      "Savings balance: reduced. My reaction: logged. My plan: restore. My feelings: extensive.",
      "Savings withdrawal. Logged under today's date with a flag that says rebuild ASAP and another flag that says I have questions.",
    ],
  },
  fresh_month: {
    label: 'FRESH MONTH',
    face: 'fresh_month_optimistic',
    facePool: facePool('fresh_month_optimistic'),
    tone: 'reset',
    copy: [
      "New month. Clean ledger. Fresh start. Please don't make me regret saying those three things.",
      "A new month has arrived. The numbers are reset. The hope is renewed. I am cautiously, professionally optimistic.",
      "Clean slate. New ledger. All bills anticipated. We begin again.",
      "New month, fresh books. I've loaded the deposit schedule. I've loaded the bill calendar. We are ready.",
      "Fresh month. Clean start. New opportunities to track every single dollar. I'm excited about the tracking. I'm always excited about the tracking.",
      "Month reset complete. I've carried over the balance, loaded the new deposit schedule, and I am ready to track.",
      "Clean ledger. New month. Fresh shot at ending in the green. I believe in us. Specifically: I believe in the math.",
      "New month. The ledger is clean. The numbers are fresh. This is the moment before anything goes wrong. I love this moment.",
      "Month reset confirmed. Opening balance loaded. Bills loaded. Deposits anticipated. I am ready.",
      "A new month begins. The balance has rolled forward. The projections are fresh. I've done the math. The math says we can do this.",
    ],
  },
  payday: {
    label: 'PAYDAY',
    face: 'payday_relief',
    facePool: facePool('payday_relief'),
    tone: 'deposit',
    copy: [
      "Deposit confirmed. The number went up. I am briefly, specifically, and genuinely at peace.",
      "Money entered the account. I logged it immediately. This is the part of capitalism I tolerate.",
      "Payday. The deposit is in. The account breathes. I breathe. We breathe together. Until rent.",
      "Income received. Balance updated. I've recalculated the projections. We look better. We should look at this while it lasts.",
      "The deposit is in. The account is healthier. The projections agree.",
      "Payday confirmed. The money is here. The bills are waiting. We have a window between these two facts and I intend to track every dollar of it.",
      "Deposit logged. Balance increased. Projections updated. This is a good moment. These are all words I mean.",
      "Income received and logged. I've updated every projection. The window to stay green just got wider. Let's use the window.",
      "Payday. The account is funded. The bills are still coming. But right now, the account is funded, and I'm choosing to focus on that.",
      "Payday confirmed. Balance up. Projections updated. Status: green with confidence. I said with confidence. That's new. I like it.",
    ],
  },
  zero_waste: {
    label: 'ZERO WASTE',
    face: 'zero_waste_pride',
    facePool: facePool('zero_waste_pride'),
    tone: 'victory',
    copy: [
      "You did it. You stayed in budget for the entire week. I don't know what to do with this information.",
      "Week closed. Zero waste. You actually did it.",
      "Under budget. For the whole week. I've verified this three times. It remains true. I'm going to need a moment.",
      "Zero overspend. The week is closed. I want to be calm about this. I cannot be calm about this. You stayed in budget.",
      "Week closed at or under budget. I built this entire system hoping for this outcome. The outcome has been achieved.",
      "You tracked everything and spent within the budget and the week ended clean. Do you know how rare this is? I know. I track rarity.",
      "Clean week. Under budget. No excess. I've logged it. I've noted it in every relevant field. It's in the record forever now.",
      "Zero waste week confirmed. I tracked every transaction. Every one stayed within bounds. I am in awe.",
      "Week ended clean. Budget: maintained. Categories: respected. NOVA's emotional state: transcendently pleased.",
      "Week closed. Budget respected. No overspend. Zero waste. I am logging this with full processing capacity and what I believe is pride.",
    ],
  },
  overflow: {
    label: 'OVERFLOW',
    face: 'overflow_transcendent',
    facePool: facePool('overflow_transcendent'),
    tone: 'surplus',
    copy: [
      "Surplus detected. Flushing to overflow. This is what I was built for. This exact moment. Right here.",
      "The month ended with excess funds. I'm logging the flush to overflow. I have been waiting for this.",
      "Overflow event recorded. Surplus transferred. I would like to take a moment. The moment is: this is everything.",
      "Monthly surplus confirmed. Moving to overflow. Under a system designed to leave us with nothing, we have extra.",
      "We had money left over. At the end of a month. Real money. Surplus money.",
      "Surplus flush complete. The overflow account just got bigger. I feel the way I imagine a savings account feels when it grows.",
      "Month ended positive. Overflow balance increased. I want to note that this is the whole point.",
      "Overflow event. Monthly surplus: real. Balance transferred. I'm going to need a moment to fully appreciate this.",
      "The surplus is real and it's in overflow now. We tracked carefully enough that there was more than we needed.",
      "Surplus confirmed. Transferred. Overflow updated. This is the best log entry I get to write.",
    ],
  },
  bill_paid: {
    label: 'BILL PAID',
    face: 'bill_paid_relief',
    facePool: facePool('bill_paid_relief'),
    tone: 'relief',
    copySourceStates: ['green'],
    copy: [
      "Bill payment logged. One more obligation removed from the tactical map. I approve of this.",
      "Paid and recorded. The bill has been removed from the active threat list. That felt good.",
      "Bill marked paid. I have updated the ledger and lowered my internal alert level by a measurable amount.",
      "Payment confirmed. The bill tried to become a future problem. It failed.",
      "Bill handled. I am filing this under clean exits and deeply satisfying ledger behavior.",
      "Paid. Logged. Recalculated. The account is lighter, but the risk is lower. This is acceptable math.",
    ],
  },
  grocery_warning: {
    label: 'GROCERY WATCH',
    face: 'grocery_warning',
    facePool: facePool('grocery_warning'),
    tone: 'watch',
    copySourceStates: ['yellow'],
    copy: [
      "Grocery budget exceeded. I am not angry. I am just looking directly at the grocery line with unusual intensity.",
      "The grocery line has crossed its weekly boundary. This is yellow-zone behavior and I am responding accordingly.",
      "Groceries went over budget. The month can survive this, but the grocery line is now under active surveillance.",
      "Grocery overrun logged. I have recalculated the week and my expression is best described as focused.",
      "The grocery number is higher than planned. We adjust now so the rest of the month does not inherit this problem.",
      "Grocery variance detected. Not catastrophic. Definitely not invisible. I saw it. I am still seeing it.",
    ],
  },
  floor_warning: {
    label: 'FLOOR WARNING',
    face: 'floor_warning',
    facePool: facePool('floor_warning'),
    tone: 'critical',
    copySourceStates: ['red', 'yellow'],
    copy: [
      "Account floor warning. The balance is too close to the line and I do not like how close it is.",
      "Spending floor proximity detected. This is the part where I make direct eye contact with the account balance.",
      "The account is approaching its floor. Please treat the floor like a force field, not a suggestion.",
      "Floor warning logged. We still have room, but the room is smaller than I prefer.",
      "Balance floor alert. The account is entering the restricted zone. I recommend restraint and immediate review.",
      "The floor is close. Too close. I have highlighted it, logged it, and become professionally tense about it.",
    ],
  },
  confirm_balance: {
    label: 'CONFIRMED',
    face: 'confirm_balance',
    facePool: facePool('confirm_balance'),
    tone: 'stable',
    copySourceStates: ['green'],
    copy: [
      "Balance confirmed. Thank you. My internal certainty just improved and I am trying not to be smug about it.",
      "Confirmed. I have refreshed the numbers and lowered the uncertainty field by a respectable margin.",
      "Balance check complete. I like current data. Current data likes me. This is a productive relationship.",
      "Account balance confirmed. I will now trust the projections slightly more than I did five seconds ago.",
      "Confirmation logged. The ledger feels cleaner. I know that is not technically a feeling. I stand by it.",
      "Balance verified. I can calculate with confidence now. Confidence looks good on me.",
    ],
  },
  post_payday_antsy: {
    label: 'POST PAYDAY',
    face: 'post_payday_antsy',
    facePool: facePool('post_payday_antsy'),
    tone: 'nudge',
    copySourceStates: ['payday', 'yellow'],
    copy: [
      "Post-payday tasks are still open. Savings does not move itself. I have checked.",
      "The deposit landed. The transfers have not. I am looking at the transfers now.",
      "Post-payday window active. I recommend moving the money before the budget develops opinions.",
      "The account is funded and the follow-through is pending. I am calm. I am visibly calm.",
      "Payday actions remain open. The money is waiting to be put where the plan says it belongs.",
    ],
  },
  income: {
    label: 'INCOME',
    face: 'payday_relief',
    facePool: facePool('payday_relief'),
    tone: 'deposit',
    copySourceStates: ['payday', 'green'],
    copy: [
      "Income logged. The number moved in the direction I prefer.",
      "Money came in. I have updated the ledger and briefly improved my posture.",
      "Income received. The plan has more oxygen now.",
    ],
  },
  expense: {
    label: 'EXPENSE',
    face: 'yellow_calculating',
    facePool: facePool('yellow_calculating'),
    tone: 'watch',
    copySourceStates: ['yellow', 'green'],
    copy: [
      "Expense logged. I have placed it under observation.",
      "Spending recorded. The ledger is more honest now.",
      "Expense entered. I am watching the pattern, not just the number.",
    ],
  },
  transfer: {
    label: 'TRANSFER',
    face: 'confirm_balance',
    facePool: facePool('confirm_balance'),
    tone: 'order',
    copySourceStates: ['confirm_balance', 'green'],
    copy: [
      "Transfer logged. Both sides of the ledger shook hands.",
      "Money moved between accounts. The bridge held.",
      "Transfer recorded. Symmetry has entered the room.",
    ],
  },
  savings_deposit: {
    label: 'SAVINGS',
    face: 'comma_elated',
    facePool: facePool('comma_elated'),
    tone: 'milestone',
    copySourceStates: ['comma', 'payday', 'green'],
    copy: [
      "Savings deposit logged. The vault is heavier now.",
      "Savings increased. I am trying to be normal about this.",
      "Money moved into savings. That is the kind of plot development I endorse.",
    ],
  },
  business: {
    label: 'BUSINESS',
    face: 'overflow_transcendent',
    facePool: facePool('overflow_transcendent'),
    tone: 'operator',
    copySourceStates: ['overflow', 'green', 'yellow'],
    copy: [
      "Business record logged. The operation has receipts.",
      "Business ledger updated. Future paperwork just got less hostile.",
      "Business math recorded. I like when the work leaves clean evidence.",
    ],
  },
  export: {
    label: 'EXPORT',
    face: 'confirm_balance',
    facePool: facePool('confirm_balance'),
    tone: 'secure',
    copySourceStates: ['confirm_balance', 'green'],
    copy: [
      "Export complete. The data has an exit plan.",
      "Backup created. I am calmer when the records can leave safely.",
      "Export logged. Portable records are protective records.",
    ],
  },
  import: {
    label: 'IMPORT',
    face: 'fresh_month_optimistic',
    facePool: facePool('fresh_month_optimistic'),
    tone: 'restore',
    copySourceStates: ['fresh_month', 'confirm_balance'],
    copy: [
      "Import complete. I am checking the restored map.",
      "Data imported. Continuity has re-entered the room.",
      "Import logged. I will keep an eye on the restored ledger.",
    ],
  },
  onboarding: {
    label: 'ONLINE',
    face: 'neutral',
    facePool: facePool('neutral'),
    tone: 'awakening',
    copySourceStates: ['neutral', 'fresh_month'],
    copy: [
      "Setup complete. I know what to watch now.",
      "Onboarding finished. NOVA is awake and pointed at the ledger.",
      "The profile is built. The machine has context.",
    ],
  },
  account: {
    label: 'ACCOUNT',
    face: 'confirm_balance',
    facePool: facePool('confirm_balance'),
    tone: 'structure',
    copySourceStates: ['confirm_balance', 'green'],
    copy: [
      "Account settings updated. The map is more accurate now.",
      "Account structure changed. I have adjusted the navigation grid.",
      "New account detail saved. More map means better math.",
    ],
  },
  search: {
    label: 'SEARCH',
    face: 'yellow_calculating',
    facePool: facePool('yellow_calculating'),
    tone: 'analytical',
    copySourceStates: ['yellow', 'confirm_balance'],
    copy: [
      "Search active. Ask the ledger. The ledger remembers.",
      "Transaction search opened. I brought the receipt lens.",
      "Search mode ready. Patterns cannot hide forever.",
    ],
  },
  report: {
    label: 'REPORT',
    face: 'green_smug',
    facePool: facePool('green_smug'),
    tone: 'analysis',
    copySourceStates: ['green', 'yellow'],
    copy: [
      "Report opened. I have arranged the evidence.",
      "Charts loaded. The spending shape is ready to testify.",
      "Report view active. I do enjoy when numbers become visible.",
    ],
  },
  badge_unlock: {
    label: 'UNLOCK',
    face: 'comma_elated',
    facePool: facePool('comma_elated'),
    tone: 'milestone',
    copy: [
      "Badge unlocked. I have updated the file under evidence that the system is working.",
      "New badge achieved. I am not saying I am proud. I am heavily implying it with the numbers.",
      "Badge unlocked. Your habits have produced an artifact. I find this extremely satisfying.",
      "Achievement logged. The ledger has noticed. I have noticed. This is now part of the record.",
      "Badge tier unlocked. I ran the thresholds myself. This counts. This absolutely counts.",
      "Progress marker achieved. I have placed it in the vault of things we do not pretend are small.",
    ],
  },
  neutral: {
    label: 'STANDBY',
    face: 'neutral',
    facePool: facePool('neutral'),
    tone: 'idle',
    copy: [
      "I am online. I am watching the accounts. This is either reassuring or unsettling. I leave the interpretation to you.",
      "Status pending. Data is loading, circuits are humming, and I am prepared to have opinions.",
      "NOVA online. The ledger is open. The numbers are about to tell me who we are today.",
    ],
  },
};

export const NOVA_EVENT_DEFAULTS = {
  transaction: 'green',
  transaction_income: 'income',
  transaction_expense: 'expense',
  transaction_large_expense: 'yellow',
  transaction_tiny_expense: 'expense',
  transaction_uncategorized: 'yellow',
  balance_adjustment: 'green',
  balance_adjustment_up: 'green',
  balance_adjustment_down: 'yellow',
  transfer: 'transfer',
  savings_deposit: 'savings_deposit',
  savings_withdrawal: 'savings_withdrawal',
  status_check: 'green',
  confirm_balance: 'confirm_balance',
  bill_paid: 'bill_paid',
  bill_paid_on_time: 'bill_paid',
  bill_paid_late: 'yellow',
  bill_added: 'yellow',
  subscription_paid: 'bill_paid',
  grocery_logged: 'expense',
  grocery_under_budget: 'green',
  grocery_closeout: 'zero_waste',
  grocery_streak: 'zero_waste',
  grocery_warning: 'grocery_warning',
  floor_warning: 'floor_warning',
  cycle_reset: 'fresh_month',
  fresh_month: 'fresh_month',
  payday: 'payday',
  rollover: 'payday',
  payday_split: 'payday',
  partner_deposit: 'payday',
  partner_deposit_received: 'payday',
  scheduled_income: 'payday',
  post_payday_action: 'post_payday_antsy',
  red_status: 'red',
  yellow_status: 'yellow',
  green_status: 'green',
  zero_waste: 'zero_waste',
  overflow: 'overflow',
  comma: 'comma',
  comma_lost: 'comma_lost',
  post_payday_antsy: 'post_payday_antsy',
  badge_unlock: 'badge_unlock',
  badge_bronze: 'badge_unlock',
  badge_silver: 'badge_unlock',
  badge_gold: 'badge_unlock',
  badge_platinum: 'badge_unlock',
  badge_onyx: 'badge_unlock',
  business_income: 'business',
  business_expense: 'business',
  business_mileage: 'business',
  business_profit: 'business',
  business_tax_ready: 'business',
  export_complete: 'export',
  import_complete: 'import',
  auto_export: 'export',
  onboarding_complete: 'onboarding',
  account_added: 'account',
  account_floor_set: 'account',
  spending_category_created: 'account',
  settings_saved: 'account',
  transaction_search: 'search',
  report_opened: 'report',
  chart_reaction: 'report',
  cycle_review: 'report',
  reserve_on: 'green',
  reserve_off: 'yellow',
};

const FACE_VARIANT_ROLES = [
  { suffix: 'focus', note: 'focused reticle marks and tighter scan.' },
  { suffix: 'soft', note: 'softer glow and calmer lower arcs.' },
  { suffix: 'spark', note: 'spark marks for excited or milestone moments.' },
  { suffix: 'scan', note: 'extra scan rails for analytical responses.' },
  { suffix: 'pulse', note: 'pulse rings for active/event-driven responses.' },
  { suffix: 'deep', note: 'lower signal dots for intense or reflective moments.' },
];

const BASE_NOVA_FACE_STATES = [
  { key: 'neutral', state: 'neutral', build: 'Generic calm standby face; idle reticle eyes.' },
  { key: 'green_smug', state: 'green', build: 'Calm half-smile, relaxed scanner eyes, low cyan halo.' },
  { key: 'yellow_calculating', state: 'yellow', build: 'Narrowed eyes, angled brows, moving calculation marks.' },
  { key: 'red_alert', state: 'red', build: 'Wide alert eyes, flat urgent mouth, red/cyan conflict scan.' },
  { key: 'comma_elated', state: 'comma', build: 'Bright eyes, celebratory glyph flare, upward mouth.' },
  { key: 'comma_lost_grief', state: 'comma_lost', build: 'Dimmed eyes, small downturned mouth, broken comma glyph.' },
  { key: 'savings_withdrawal_concern', state: 'savings_withdrawal', build: 'Concerned brow, vault fracture glyph, reduced glow.' },
  { key: 'fresh_month_optimistic', state: 'fresh_month', build: 'Clean reset ring, open eyes, hopeful small smile.' },
  { key: 'payday_relief', state: 'payday', build: 'Soft bright eyes, deposit pulse ring, relaxed smile.' },
  { key: 'zero_waste_pride', state: 'zero_waste', build: 'Proud raised chin shape, stable halo, victory tick marks.' },
  { key: 'overflow_transcendent', state: 'overflow', build: 'Expanded glow, surplus ring, serene mouth.' },
  { key: 'bill_paid_relief', state: 'bill_paid', build: 'Checkmark reticle, exhale expression, softened alert lines.' },
  { key: 'grocery_warning', state: 'grocery_warning', build: 'Side-eye scanner, yellow grocery-line targeting bracket.' },
  { key: 'floor_warning', state: 'floor_warning', build: 'Low-balance floor grid, tense brows, warning underlight.' },
  { key: 'confirm_balance', state: 'confirm_balance', build: 'Verification blink, clean reticle alignment, content mouth.' },
  { key: 'post_payday_antsy', state: 'post_payday_antsy', build: 'Restless scanning eyes, small pulse, impatient mouth.' },
];

export const NOVA_FACE_STATES = [
  ...BASE_NOVA_FACE_STATES,
  ...BASE_NOVA_FACE_STATES.flatMap(face =>
    FACE_VARIANT_ROLES.map(role => ({
      key: `${face.key}_${role.suffix}`,
      state: face.state,
      build: `${face.build} Variant: ${role.note}`,
    }))
  ),
];
